---
title: "Tugas 1 Praktikum - Teknik Peubah Ganda"
author: "Elardian Putera Ramadhan (G1401231042)"
date: "2025-08-21"
output:
  html_document:
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: true
    highlight: tango
    code_folding: show
    toc_depth: 5
    number_sections: false
    theme: flatly
    toc: yes
    toc_float:
      collapsed: true
      smooth_scroll: true
    fig_caption: true
---

## Latihan 1

Diketahui matriks A, B, dan C berikut

$$
A = \begin{bmatrix} 9 & 1 \\ 1 & 9 \end{bmatrix}
\qquad
B = \begin{bmatrix} 2 & 0 & 0 \\ 0 & 4 & 0 \\ 0 & 0 & 0 \end{bmatrix}
\qquad
C = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}
$$

1.  Tentukan akar ciri dan vektor ciri dari matriks A, B, dan C!

```{r}
# Membuat Matriks A
A <- matrix(c(9, 1, 1, 9), nrow = 2, byrow = TRUE)
A

# Menghitung akar ciri dari A
AkarCiri_A <- eigen(A)$values
AkarCiri_A

# Menghitung vektor ciri dari A
VektorCiri_A <- eigen(A)$vectors
VektorCiri_A

# Membuat Matriks B
B <- matrix(c(2, 0, 0, 0, 4, 0, 0, 0, 0), nrow = 3, byrow = TRUE)
B

# Menghitung akar ciri dari B
AkarCiri_B <- eigen(B)$values
AkarCiri_B

# Menghitung vektor ciri dari B
VektorCiri_B <- eigen(B)$vectors
VektorCiri_B

# Membuat Matriks C
C <- diag(3)
C

# Menghitung akar ciri dari C
AkarCiri_C <- eigen(C)$values
AkarCiri_C

# Menghitung vektor ciri dari C
VektorCiri_C <- eigen(C)$vectors
VektorCiri_C
```

2.  Apakah matriks A, B, dan C merupakan matriks definit positif?

```{r}
# Fungsi untuk memeriksa apakah matriks adalah definit positif
is_positive_definite <- function(mat) {
  # Pastikan matriksnya simetris
  if (!isSymmetric(mat)) {
    return(FALSE)
  }
  
  # Hitung nilai eigen
  eigenvalues <- eigen(mat, only.values = TRUE)$values
  
  # Periksa apakah semua nilai eigen > 0
  return(all(eigenvalues > 1e-8)) # Menggunakan toleransi kecil untuk presisi numerik
}

# Mendefinisikan matriks A, B, dan C
A <- matrix(c(9, 1, 1, 9), nrow = 2, byrow = TRUE)
B <- matrix(c(2, 0, 0, 0, 4, 0, 0, 0, 0), nrow = 3, byrow = TRUE)
C <- diag(3)

# Menampilkan matriks
A
B
C

# Memeriksa dan mencetak hasilnya
cat("\nApakah matriks A definit positif?", is_positive_definite(A), "\n")
cat("Apakah matriks B definit positif?", is_positive_definite(B), "\n")
cat("Apakah matriks C definit positif?", is_positive_definite(C), "\n")
```


## Latihan 2

Suatu matriks ragam peragam sebagai berikut

$$
\Sigma = \begin{bmatrix} 25 & -2 & 4 \\ -2 & 4 & 1 \\ 4 & 1 & 9 \end{bmatrix}
$$

1.  Tentukan matriks korelasi dari matriks ragam peragam tersebut!

```{r}
# Membuat matriks ragam peragam
Sigma <- matrix(c(25, -2, 4, -2, 4, 1, 4, 1, 9), nrow = 3, byrow = TRUE)
Sigma

# Menghitung matriks korelasi
correlation_matrix <- cov2cor(Sigma)
correlation_matrix
```
